version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    networks:
      moodSickNetwork-10.9.0.0:
        ipv4_address: 10.9.0.5

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    # volumes:
    #   - ./middleware:/app
    networks:
      moodSickNetwork-10.9.0.0:
        ipv4_address: 10.9.0.6

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    tty: true
    ports:
      - 5000:5000
    networks:
     moodSickNetwork-10.9.0.0:
        ipv4_address: 10.9.0.7
  
  mongodb:
    platform: linux/arm64/v8
    image: mongo:7.0.4-rc0
    ports:
      - "27017:27017"
    tty: true
    networks:
      moodSickNetwork-10.9.0.0:
        ipv4_address: 10.9.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: moodSickDB

networks:
  moodSickNetwork-10.9.0.0:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.0.0/24