version: '3.8'
services:
  ml_training:
    platform: linux/arm64/v8
    build:
      context: ./ml_training
      dockerfile: Dockerfile
    image: ml_training
    tty: true
    volumes:
      - ./ml_training:/ml_training
    env_file:
      - ./ml_training/.env